# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name_period = QtWidgets.QLabel(self.centralwidget)
        self.label_name_period.setGeometry(QtCore.QRect(10, 10, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name_period.setFont(font)
        self.label_name_period.setObjectName("label_name_period")
        self.tab01_input_period = QtWidgets.QLineEdit(self.centralwidget)
        self.tab01_input_period.setEnabled(False)
        self.tab01_input_period.setGeometry(QtCore.QRect(190, 10, 120, 30))
        self.tab01_input_period.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab01_input_period.setText("")
        self.tab01_input_period.setObjectName("tab01_input_period")
        self.label_name_reporter = QtWidgets.QLabel(self.centralwidget)
        self.label_name_reporter.setGeometry(QtCore.QRect(10, 50, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name_reporter.setFont(font)
        self.label_name_reporter.setObjectName("label_name_reporter")
        self.label_name_partner = QtWidgets.QLabel(self.centralwidget)
        self.label_name_partner.setGeometry(QtCore.QRect(10, 90, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name_partner.setFont(font)
        self.label_name_partner.setObjectName("label_name_partner")
        self.label_name_trade_flow = QtWidgets.QLabel(self.centralwidget)
        self.label_name_trade_flow.setGeometry(QtCore.QRect(10, 130, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name_trade_flow.setFont(font)
        self.label_name_trade_flow.setObjectName("label_name_trade_flow")
        self.tab02_select_reporter = QtWidgets.QComboBox(self.centralwidget)
        self.tab02_select_reporter.setEnabled(False)
        self.tab02_select_reporter.setGeometry(QtCore.QRect(190, 50, 120, 30))
        self.tab02_select_reporter.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab02_select_reporter.setObjectName("tab02_select_reporter")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab02_select_reporter.addItem("")
        self.tab03_select_partner = QtWidgets.QComboBox(self.centralwidget)
        self.tab03_select_partner.setEnabled(False)
        self.tab03_select_partner.setGeometry(QtCore.QRect(190, 90, 120, 30))
        self.tab03_select_partner.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab03_select_partner.setObjectName("tab03_select_partner")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab03_select_partner.addItem("")
        self.tab04_select_trade_flow = QtWidgets.QComboBox(self.centralwidget)
        self.tab04_select_trade_flow.setEnabled(False)
        self.tab04_select_trade_flow.setGeometry(QtCore.QRect(190, 130, 120, 30))
        self.tab04_select_trade_flow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab04_select_trade_flow.setObjectName("tab04_select_trade_flow")
        self.tab04_select_trade_flow.addItem("")
        self.tab04_select_trade_flow.addItem("")
        self.tab04_select_trade_flow.addItem("")
        self.tab04_select_trade_flow.addItem("")
        self.tab04_select_trade_flow.addItem("")
        self.tab04_select_trade_flow.addItem("")
        self.label_name_start_index = QtWidgets.QLabel(self.centralwidget)
        self.label_name_start_index.setGeometry(QtCore.QRect(10, 210, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name_start_index.setFont(font)
        self.label_name_start_index.setObjectName("label_name_start_index")
        self.tab09_input_start_index = QtWidgets.QLineEdit(self.centralwidget)
        self.tab09_input_start_index.setEnabled(False)
        self.tab09_input_start_index.setGeometry(QtCore.QRect(190, 210, 120, 30))
        self.tab09_input_start_index.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab09_input_start_index.setObjectName("tab09_input_start_index")
        self.btn_get_data = QtWidgets.QPushButton(self.centralwidget)
        self.btn_get_data.setEnabled(False)
        self.btn_get_data.setGeometry(QtCore.QRect(700, 210, 130, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_get_data.setFont(font)
        self.btn_get_data.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_get_data.setObjectName("btn_get_data")
        self.text_message = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_message.setGeometry(QtCore.QRect(10, 300, 1000, 415))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.text_message.setFont(font)
        self.text_message.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.text_message.setObjectName("text_message")
        self.label_name_end_index = QtWidgets.QLabel(self.centralwidget)
        self.label_name_end_index.setGeometry(QtCore.QRect(10, 250, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name_end_index.setFont(font)
        self.label_name_end_index.setObjectName("label_name_end_index")
        self.tab10_input_end_index = QtWidgets.QLineEdit(self.centralwidget)
        self.tab10_input_end_index.setEnabled(False)
        self.tab10_input_end_index.setGeometry(QtCore.QRect(190, 250, 120, 30))
        self.tab10_input_end_index.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab10_input_end_index.setObjectName("tab10_input_end_index")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(342, 0, 361, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab05_radio_freq_year = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.tab05_radio_freq_year.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab05_radio_freq_year.setChecked(True)
        self.tab05_radio_freq_year.setAutoExclusive(True)
        self.tab05_radio_freq_year.setObjectName("tab05_radio_freq_year")
        self.horizontalLayout.addWidget(self.tab05_radio_freq_year)
        self.tab06_radio_freq_month = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.tab06_radio_freq_month.setTabletTracking(False)
        self.tab06_radio_freq_month.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab06_radio_freq_month.setChecked(False)
        self.tab06_radio_freq_month.setAutoExclusive(True)
        self.tab06_radio_freq_month.setObjectName("tab06_radio_freq_month")
        self.horizontalLayout.addWidget(self.tab06_radio_freq_month)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setEnabled(True)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(330, 50, 371, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.check_5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_5.setEnabled(False)
        self.check_5.setObjectName("check_5")
        self.gridLayout_3.addWidget(self.check_5, 2, 0, 1, 1)
        self.check_all = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_all.setEnabled(False)
        self.check_all.setCheckable(True)
        self.check_all.setChecked(False)
        self.check_all.setAutoRepeat(False)
        self.check_all.setAutoExclusive(True)
        self.check_all.setObjectName("check_all")
        self.gridLayout_3.addWidget(self.check_all, 0, 0, 1, 1)
        self.check_7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_7.setEnabled(False)
        self.check_7.setObjectName("check_7")
        self.gridLayout_3.addWidget(self.check_7, 2, 2, 1, 1)
        self.check_6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_6.setEnabled(False)
        self.check_6.setObjectName("check_6")
        self.gridLayout_3.addWidget(self.check_6, 2, 1, 1, 1)
        self.check_8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_8.setEnabled(False)
        self.check_8.setObjectName("check_8")
        self.gridLayout_3.addWidget(self.check_8, 2, 3, 1, 1)
        self.check_1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_1.setEnabled(False)
        self.check_1.setObjectName("check_1")
        self.gridLayout_3.addWidget(self.check_1, 1, 0, 1, 1)
        self.check_9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_9.setEnabled(False)
        self.check_9.setObjectName("check_9")
        self.gridLayout_3.addWidget(self.check_9, 3, 0, 1, 1)
        self.check_10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_10.setEnabled(False)
        self.check_10.setObjectName("check_10")
        self.gridLayout_3.addWidget(self.check_10, 3, 1, 1, 1)
        self.check_11 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_11.setEnabled(False)
        self.check_11.setObjectName("check_11")
        self.gridLayout_3.addWidget(self.check_11, 3, 2, 1, 1)
        self.check_12 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_12.setEnabled(False)
        self.check_12.setObjectName("check_12")
        self.gridLayout_3.addWidget(self.check_12, 3, 3, 1, 1)
        self.check_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_2.setEnabled(False)
        self.check_2.setObjectName("check_2")
        self.gridLayout_3.addWidget(self.check_2, 1, 1, 1, 1)
        self.check_4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_4.setEnabled(False)
        self.check_4.setObjectName("check_4")
        self.gridLayout_3.addWidget(self.check_4, 1, 3, 1, 1)
        self.check_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.check_3.setEnabled(False)
        self.check_3.setObjectName("check_3")
        self.gridLayout_3.addWidget(self.check_3, 1, 2, 1, 1)
        self.label_name_start_hs = QtWidgets.QLabel(self.centralwidget)
        self.label_name_start_hs.setGeometry(QtCore.QRect(350, 210, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name_start_hs.setFont(font)
        self.label_name_start_hs.setObjectName("label_name_start_hs")
        self.label_name_end_hs = QtWidgets.QLabel(self.centralwidget)
        self.label_name_end_hs.setGeometry(QtCore.QRect(350, 250, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_name_end_hs.setFont(font)
        self.label_name_end_hs.setObjectName("label_name_end_hs")
        self.tab11_input_start_hs = QtWidgets.QLineEdit(self.centralwidget)
        self.tab11_input_start_hs.setEnabled(False)
        self.tab11_input_start_hs.setGeometry(QtCore.QRect(530, 210, 120, 30))
        self.tab11_input_start_hs.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab11_input_start_hs.setObjectName("tab11_input_start_hs")
        self.tab12_input_end_hs = QtWidgets.QLineEdit(self.centralwidget)
        self.tab12_input_end_hs.setEnabled(False)
        self.tab12_input_end_hs.setGeometry(QtCore.QRect(530, 250, 120, 30))
        self.tab12_input_end_hs.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab12_input_end_hs.setObjectName("tab12_input_end_hs")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 661, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tab07_radio_index = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.tab07_radio_index.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab07_radio_index.setChecked(True)
        self.tab07_radio_index.setObjectName("tab07_radio_index")
        self.horizontalLayout_2.addWidget(self.tab07_radio_index)
        self.tab08_radio_hs = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.tab08_radio_hs.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab08_radio_hs.setObjectName("tab08_radio_hs")
        self.horizontalLayout_2.addWidget(self.tab08_radio_hs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        MainWindow.setTabOrder(self.tab01_input_period, self.tab02_select_reporter)
        MainWindow.setTabOrder(self.tab02_select_reporter, self.tab03_select_partner)
        MainWindow.setTabOrder(self.tab03_select_partner, self.tab04_select_trade_flow)
        MainWindow.setTabOrder(self.tab04_select_trade_flow, self.tab05_radio_freq_year)
        MainWindow.setTabOrder(self.tab05_radio_freq_year, self.tab06_radio_freq_month)
        MainWindow.setTabOrder(self.tab06_radio_freq_month, self.tab07_radio_index)
        MainWindow.setTabOrder(self.tab07_radio_index, self.tab08_radio_hs)
        MainWindow.setTabOrder(self.tab08_radio_hs, self.tab09_input_start_index)
        MainWindow.setTabOrder(self.tab09_input_start_index, self.tab10_input_end_index)
        MainWindow.setTabOrder(self.tab10_input_end_index, self.tab11_input_start_hs)
        MainWindow.setTabOrder(self.tab11_input_start_hs, self.tab12_input_end_hs)
        MainWindow.setTabOrder(self.tab12_input_end_hs, self.tab01_input_period)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name_period.setText(_translate("MainWindow", "Period(Year) :"))
        self.label_name_reporter.setText(_translate("MainWindow", "Reporter       :"))
        self.label_name_partner.setText(_translate("MainWindow", "Partner         :"))
        self.label_name_trade_flow.setText(_translate("MainWindow", "Trade Flow   :"))
        self.tab02_select_reporter.setItemText(0, _translate("MainWindow", "None"))
        self.tab02_select_reporter.setItemText(1, _translate("MainWindow", "All"))
        self.tab02_select_reporter.setItemText(2, _translate("MainWindow", "World"))
        self.tab02_select_reporter.setItemText(3, _translate("MainWindow", "Afghanistan"))
        self.tab02_select_reporter.setItemText(4, _translate("MainWindow", "Africa CAMEU region, nes"))
        self.tab02_select_reporter.setItemText(5, _translate("MainWindow", "Albania"))
        self.tab02_select_reporter.setItemText(6, _translate("MainWindow", "Algeria"))
        self.tab02_select_reporter.setItemText(7, _translate("MainWindow", "American Samoa"))
        self.tab02_select_reporter.setItemText(8, _translate("MainWindow", "Andorra"))
        self.tab02_select_reporter.setItemText(9, _translate("MainWindow", "Angola"))
        self.tab02_select_reporter.setItemText(10, _translate("MainWindow", "Anguilla"))
        self.tab02_select_reporter.setItemText(11, _translate("MainWindow", "Antarctica"))
        self.tab02_select_reporter.setItemText(12, _translate("MainWindow", "Antigua and Barbuda"))
        self.tab02_select_reporter.setItemText(13, _translate("MainWindow", "Areas, nes"))
        self.tab02_select_reporter.setItemText(14, _translate("MainWindow", "Argentina"))
        self.tab02_select_reporter.setItemText(15, _translate("MainWindow", "Armenia"))
        self.tab02_select_reporter.setItemText(16, _translate("MainWindow", "Aruba"))
        self.tab02_select_reporter.setItemText(17, _translate("MainWindow", "Australia"))
        self.tab02_select_reporter.setItemText(18, _translate("MainWindow", "Austria"))
        self.tab02_select_reporter.setItemText(19, _translate("MainWindow", "Azerbaijan"))
        self.tab02_select_reporter.setItemText(20, _translate("MainWindow", "Bahamas"))
        self.tab02_select_reporter.setItemText(21, _translate("MainWindow", "Bahrain"))
        self.tab02_select_reporter.setItemText(22, _translate("MainWindow", "Bangladesh"))
        self.tab02_select_reporter.setItemText(23, _translate("MainWindow", "Barbados"))
        self.tab02_select_reporter.setItemText(24, _translate("MainWindow", "Belarus"))
        self.tab02_select_reporter.setItemText(25, _translate("MainWindow", "Belgium"))
        self.tab02_select_reporter.setItemText(26, _translate("MainWindow", "Belgium-Luxembourg"))
        self.tab02_select_reporter.setItemText(27, _translate("MainWindow", "Belize"))
        self.tab02_select_reporter.setItemText(28, _translate("MainWindow", "Benin"))
        self.tab02_select_reporter.setItemText(29, _translate("MainWindow", "Bermuda"))
        self.tab02_select_reporter.setItemText(30, _translate("MainWindow", "Bhutan"))
        self.tab02_select_reporter.setItemText(31, _translate("MainWindow", "Bolivia (Plurinational State of)"))
        self.tab02_select_reporter.setItemText(32, _translate("MainWindow", "Bonaire"))
        self.tab02_select_reporter.setItemText(33, _translate("MainWindow", "Bosnia Herzegovina"))
        self.tab02_select_reporter.setItemText(34, _translate("MainWindow", "Botswana"))
        self.tab02_select_reporter.setItemText(35, _translate("MainWindow", "Bouvet Island"))
        self.tab02_select_reporter.setItemText(36, _translate("MainWindow", "Br. Antarctic Terr."))
        self.tab02_select_reporter.setItemText(37, _translate("MainWindow", "Br. Indian Ocean Terr."))
        self.tab02_select_reporter.setItemText(38, _translate("MainWindow", "Br. Virgin Isds"))
        self.tab02_select_reporter.setItemText(39, _translate("MainWindow", "Brazil"))
        self.tab02_select_reporter.setItemText(40, _translate("MainWindow", "Brunei Darussalam"))
        self.tab02_select_reporter.setItemText(41, _translate("MainWindow", "Bulgaria"))
        self.tab02_select_reporter.setItemText(42, _translate("MainWindow", "Bunkers"))
        self.tab02_select_reporter.setItemText(43, _translate("MainWindow", "Burkina Faso"))
        self.tab02_select_reporter.setItemText(44, _translate("MainWindow", "Burundi"))
        self.tab02_select_reporter.setItemText(45, _translate("MainWindow", "Cabo Verde"))
        self.tab02_select_reporter.setItemText(46, _translate("MainWindow", "CACM, nes"))
        self.tab02_select_reporter.setItemText(47, _translate("MainWindow", "Cambodia"))
        self.tab02_select_reporter.setItemText(48, _translate("MainWindow", "Cameroon"))
        self.tab02_select_reporter.setItemText(49, _translate("MainWindow", "Canada"))
        self.tab02_select_reporter.setItemText(50, _translate("MainWindow", "Caribbean, nes"))
        self.tab02_select_reporter.setItemText(51, _translate("MainWindow", "Cayman Isds"))
        self.tab02_select_reporter.setItemText(52, _translate("MainWindow", "Central African Rep."))
        self.tab02_select_reporter.setItemText(53, _translate("MainWindow", "Chad"))
        self.tab02_select_reporter.setItemText(54, _translate("MainWindow", "Chile"))
        self.tab02_select_reporter.setItemText(55, _translate("MainWindow", "China"))
        self.tab02_select_reporter.setItemText(56, _translate("MainWindow", "China, Hong Kong SAR"))
        self.tab02_select_reporter.setItemText(57, _translate("MainWindow", "China, Macao SAR"))
        self.tab02_select_reporter.setItemText(58, _translate("MainWindow", "Christmas Isds"))
        self.tab02_select_reporter.setItemText(59, _translate("MainWindow", "Cocos Isds"))
        self.tab02_select_reporter.setItemText(60, _translate("MainWindow", "Colombia"))
        self.tab02_select_reporter.setItemText(61, _translate("MainWindow", "Comoros"))
        self.tab02_select_reporter.setItemText(62, _translate("MainWindow", "Congo"))
        self.tab02_select_reporter.setItemText(63, _translate("MainWindow", "Cook Isds"))
        self.tab02_select_reporter.setItemText(64, _translate("MainWindow", "Costa Rica"))
        self.tab02_select_reporter.setItemText(65, _translate("MainWindow", "Côte d\'Ivoire"))
        self.tab02_select_reporter.setItemText(66, _translate("MainWindow", "Croatia"))
        self.tab02_select_reporter.setItemText(67, _translate("MainWindow", "Cuba"))
        self.tab02_select_reporter.setItemText(68, _translate("MainWindow", "Curaçao"))
        self.tab02_select_reporter.setItemText(69, _translate("MainWindow", "Cyprus"))
        self.tab02_select_reporter.setItemText(70, _translate("MainWindow", "Czechia"))
        self.tab02_select_reporter.setItemText(71, _translate("MainWindow", "Czechoslovakia"))
        self.tab02_select_reporter.setItemText(72, _translate("MainWindow", "Dem. People\'s Rep. of Korea"))
        self.tab02_select_reporter.setItemText(73, _translate("MainWindow", "Dem. Rep. of the Congo"))
        self.tab02_select_reporter.setItemText(74, _translate("MainWindow", "Denmark"))
        self.tab02_select_reporter.setItemText(75, _translate("MainWindow", "Djibouti"))
        self.tab02_select_reporter.setItemText(76, _translate("MainWindow", "Dominica"))
        self.tab02_select_reporter.setItemText(77, _translate("MainWindow", "Dominican Rep."))
        self.tab02_select_reporter.setItemText(78, _translate("MainWindow", "East and West Pakistan"))
        self.tab02_select_reporter.setItemText(79, _translate("MainWindow", "Eastern Europe, nes"))
        self.tab02_select_reporter.setItemText(80, _translate("MainWindow", "Ecuador"))
        self.tab02_select_reporter.setItemText(81, _translate("MainWindow", "Egypt"))
        self.tab02_select_reporter.setItemText(82, _translate("MainWindow", "El Salvador"))
        self.tab02_select_reporter.setItemText(83, _translate("MainWindow", "Equatorial Guinea"))
        self.tab02_select_reporter.setItemText(84, _translate("MainWindow", "Eritrea"))
        self.tab02_select_reporter.setItemText(85, _translate("MainWindow", "Estonia"))
        self.tab02_select_reporter.setItemText(86, _translate("MainWindow", "Ethiopia"))
        self.tab02_select_reporter.setItemText(87, _translate("MainWindow", "Europe EFTA, nes"))
        self.tab02_select_reporter.setItemText(88, _translate("MainWindow", "Europe EU, nes"))
        self.tab02_select_reporter.setItemText(89, _translate("MainWindow", "Faeroe Isds"))
        self.tab02_select_reporter.setItemText(90, _translate("MainWindow", "Falkland Isds (Malvinas)"))
        self.tab02_select_reporter.setItemText(91, _translate("MainWindow", "Fiji"))
        self.tab02_select_reporter.setItemText(92, _translate("MainWindow", "Finland"))
        self.tab02_select_reporter.setItemText(93, _translate("MainWindow", "Fmr Arab Rep. of Yemen"))
        self.tab02_select_reporter.setItemText(94, _translate("MainWindow", "Fmr Dem. Rep. of Germany"))
        self.tab02_select_reporter.setItemText(95, _translate("MainWindow", "Fmr Dem. Rep. of Vietnam"))
        self.tab02_select_reporter.setItemText(96, _translate("MainWindow", "Fmr Dem. Yemen"))
        self.tab02_select_reporter.setItemText(97, _translate("MainWindow", "Fmr Ethiopia"))
        self.tab02_select_reporter.setItemText(98, _translate("MainWindow", "Fmr Fed. Rep. of Germany"))
        self.tab02_select_reporter.setItemText(99, _translate("MainWindow", "Fmr Pacific Isds"))
        self.tab02_select_reporter.setItemText(100, _translate("MainWindow", "Fmr Panama, excl.Canal Zone"))
        self.tab02_select_reporter.setItemText(101, _translate("MainWindow", "Fmr Panama-Canal-Zone"))
        self.tab02_select_reporter.setItemText(102, _translate("MainWindow", "Fmr Rep. of Vietnam"))
        self.tab02_select_reporter.setItemText(103, _translate("MainWindow", "Fmr Rhodesia Nyas"))
        self.tab02_select_reporter.setItemText(104, _translate("MainWindow", "Fmr Sudan"))
        self.tab02_select_reporter.setItemText(105, _translate("MainWindow", "Fmr Tanganyika"))
        self.tab02_select_reporter.setItemText(106, _translate("MainWindow", "Fmr USSR"))
        self.tab02_select_reporter.setItemText(107, _translate("MainWindow", "Fmr Yugoslavia"))
        self.tab02_select_reporter.setItemText(108, _translate("MainWindow", "Fmr Zanzibar and Pemba Isd"))
        self.tab02_select_reporter.setItemText(109, _translate("MainWindow", "Fr. South Antarctic Terr."))
        self.tab02_select_reporter.setItemText(110, _translate("MainWindow", "France"))
        self.tab02_select_reporter.setItemText(111, _translate("MainWindow", "Free Zones"))
        self.tab02_select_reporter.setItemText(112, _translate("MainWindow", "French Guiana"))
        self.tab02_select_reporter.setItemText(113, _translate("MainWindow", "French Polynesia"))
        self.tab02_select_reporter.setItemText(114, _translate("MainWindow", "FS Micronesia"))
        self.tab02_select_reporter.setItemText(115, _translate("MainWindow", "Gabon"))
        self.tab02_select_reporter.setItemText(116, _translate("MainWindow", "Gambia"))
        self.tab02_select_reporter.setItemText(117, _translate("MainWindow", "Georgia"))
        self.tab02_select_reporter.setItemText(118, _translate("MainWindow", "Germany"))
        self.tab02_select_reporter.setItemText(119, _translate("MainWindow", "Ghana"))
        self.tab02_select_reporter.setItemText(120, _translate("MainWindow", "Gibraltar"))
        self.tab02_select_reporter.setItemText(121, _translate("MainWindow", "Greece"))
        self.tab02_select_reporter.setItemText(122, _translate("MainWindow", "Greenland"))
        self.tab02_select_reporter.setItemText(123, _translate("MainWindow", "Grenada"))
        self.tab02_select_reporter.setItemText(124, _translate("MainWindow", "Guadeloupe"))
        self.tab02_select_reporter.setItemText(125, _translate("MainWindow", "Guam"))
        self.tab02_select_reporter.setItemText(126, _translate("MainWindow", "Guatemala"))
        self.tab02_select_reporter.setItemText(127, _translate("MainWindow", "Guinea"))
        self.tab02_select_reporter.setItemText(128, _translate("MainWindow", "Guinea-Bissau"))
        self.tab02_select_reporter.setItemText(129, _translate("MainWindow", "Guyana"))
        self.tab02_select_reporter.setItemText(130, _translate("MainWindow", "Haiti"))
        self.tab02_select_reporter.setItemText(131, _translate("MainWindow", "Heard Island and McDonald Islands"))
        self.tab02_select_reporter.setItemText(132, _translate("MainWindow", "Holy See (Vatican City State)"))
        self.tab02_select_reporter.setItemText(133, _translate("MainWindow", "Honduras"))
        self.tab02_select_reporter.setItemText(134, _translate("MainWindow", "Hungary"))
        self.tab02_select_reporter.setItemText(135, _translate("MainWindow", "Iceland"))
        self.tab02_select_reporter.setItemText(136, _translate("MainWindow", "India"))
        self.tab02_select_reporter.setItemText(137, _translate("MainWindow", "India, excl. Sikkim"))
        self.tab02_select_reporter.setItemText(138, _translate("MainWindow", "Indonesia"))
        self.tab02_select_reporter.setItemText(139, _translate("MainWindow", "Iran"))
        self.tab02_select_reporter.setItemText(140, _translate("MainWindow", "Iraq"))
        self.tab02_select_reporter.setItemText(141, _translate("MainWindow", "Ireland"))
        self.tab02_select_reporter.setItemText(142, _translate("MainWindow", "Israel"))
        self.tab02_select_reporter.setItemText(143, _translate("MainWindow", "Italy"))
        self.tab02_select_reporter.setItemText(144, _translate("MainWindow", "Jamaica"))
        self.tab02_select_reporter.setItemText(145, _translate("MainWindow", "Japan"))
        self.tab02_select_reporter.setItemText(146, _translate("MainWindow", "Jordan"))
        self.tab02_select_reporter.setItemText(147, _translate("MainWindow", "Kazakhstan"))
        self.tab02_select_reporter.setItemText(148, _translate("MainWindow", "Kenya"))
        self.tab02_select_reporter.setItemText(149, _translate("MainWindow", "Kiribati"))
        self.tab02_select_reporter.setItemText(150, _translate("MainWindow", "Kuwait"))
        self.tab02_select_reporter.setItemText(151, _translate("MainWindow", "Kyrgyzstan"))
        self.tab02_select_reporter.setItemText(152, _translate("MainWindow", "LAIA, nes"))
        self.tab02_select_reporter.setItemText(153, _translate("MainWindow", "Lao People\'s Dem. Rep."))
        self.tab02_select_reporter.setItemText(154, _translate("MainWindow", "Latvia"))
        self.tab02_select_reporter.setItemText(155, _translate("MainWindow", "Lebanon"))
        self.tab02_select_reporter.setItemText(156, _translate("MainWindow", "Lesotho"))
        self.tab02_select_reporter.setItemText(157, _translate("MainWindow", "Liberia"))
        self.tab02_select_reporter.setItemText(158, _translate("MainWindow", "Libya"))
        self.tab02_select_reporter.setItemText(159, _translate("MainWindow", "Lithuania"))
        self.tab02_select_reporter.setItemText(160, _translate("MainWindow", "Luxembourg"))
        self.tab02_select_reporter.setItemText(161, _translate("MainWindow", "Madagascar"))
        self.tab02_select_reporter.setItemText(162, _translate("MainWindow", "Malawi"))
        self.tab02_select_reporter.setItemText(163, _translate("MainWindow", "Malaysia"))
        self.tab02_select_reporter.setItemText(164, _translate("MainWindow", "Maldives"))
        self.tab02_select_reporter.setItemText(165, _translate("MainWindow", "Mali"))
        self.tab02_select_reporter.setItemText(166, _translate("MainWindow", "Malta"))
        self.tab02_select_reporter.setItemText(167, _translate("MainWindow", "Marshall Isds"))
        self.tab02_select_reporter.setItemText(168, _translate("MainWindow", "Martinique"))
        self.tab02_select_reporter.setItemText(169, _translate("MainWindow", "Mauritania"))
        self.tab02_select_reporter.setItemText(170, _translate("MainWindow", "Mauritius"))
        self.tab02_select_reporter.setItemText(171, _translate("MainWindow", "Mayotte"))
        self.tab02_select_reporter.setItemText(172, _translate("MainWindow", "Mexico"))
        self.tab02_select_reporter.setItemText(173, _translate("MainWindow", "Mongolia"))
        self.tab02_select_reporter.setItemText(174, _translate("MainWindow", "Montenegro"))
        self.tab02_select_reporter.setItemText(175, _translate("MainWindow", "Montserrat"))
        self.tab02_select_reporter.setItemText(176, _translate("MainWindow", "Morocco"))
        self.tab02_select_reporter.setItemText(177, _translate("MainWindow", "Mozambique"))
        self.tab02_select_reporter.setItemText(178, _translate("MainWindow", "Myanmar"))
        self.tab02_select_reporter.setItemText(179, _translate("MainWindow", "N. Mariana Isds"))
        self.tab02_select_reporter.setItemText(180, _translate("MainWindow", "Namibia"))
        self.tab02_select_reporter.setItemText(181, _translate("MainWindow", "Nauru"))
        self.tab02_select_reporter.setItemText(182, _translate("MainWindow", "Nepal"))
        self.tab02_select_reporter.setItemText(183, _translate("MainWindow", "Neth. Antilles"))
        self.tab02_select_reporter.setItemText(184, _translate("MainWindow", "Neth. Antilles and Aruba"))
        self.tab02_select_reporter.setItemText(185, _translate("MainWindow", "Netherlands"))
        self.tab02_select_reporter.setItemText(186, _translate("MainWindow", "Neutral Zone"))
        self.tab02_select_reporter.setItemText(187, _translate("MainWindow", "New Caledonia"))
        self.tab02_select_reporter.setItemText(188, _translate("MainWindow", "New Zealand"))
        self.tab02_select_reporter.setItemText(189, _translate("MainWindow", "Nicaragua"))
        self.tab02_select_reporter.setItemText(190, _translate("MainWindow", "Niger"))
        self.tab02_select_reporter.setItemText(191, _translate("MainWindow", "Nigeria"))
        self.tab02_select_reporter.setItemText(192, _translate("MainWindow", "Niue"))
        self.tab02_select_reporter.setItemText(193, _translate("MainWindow", "Norfolk Isds"))
        self.tab02_select_reporter.setItemText(194, _translate("MainWindow", "North America and Central America, nes"))
        self.tab02_select_reporter.setItemText(195, _translate("MainWindow", "Northern Africa, nes"))
        self.tab02_select_reporter.setItemText(196, _translate("MainWindow", "Norway"))
        self.tab02_select_reporter.setItemText(197, _translate("MainWindow", "Oceania, nes"))
        self.tab02_select_reporter.setItemText(198, _translate("MainWindow", "Oman"))
        self.tab02_select_reporter.setItemText(199, _translate("MainWindow", "Other Africa, nes"))
        self.tab02_select_reporter.setItemText(200, _translate("MainWindow", "Other Asia, nes"))
        self.tab02_select_reporter.setItemText(201, _translate("MainWindow", "Other Europe, nes"))
        self.tab02_select_reporter.setItemText(202, _translate("MainWindow", "Pakistan"))
        self.tab02_select_reporter.setItemText(203, _translate("MainWindow", "Palau"))
        self.tab02_select_reporter.setItemText(204, _translate("MainWindow", "Panama"))
        self.tab02_select_reporter.setItemText(205, _translate("MainWindow", "Papua New Guinea"))
        self.tab02_select_reporter.setItemText(206, _translate("MainWindow", "Paraguay"))
        self.tab02_select_reporter.setItemText(207, _translate("MainWindow", "Peninsula Malaysia"))
        self.tab02_select_reporter.setItemText(208, _translate("MainWindow", "Peru"))
        self.tab02_select_reporter.setItemText(209, _translate("MainWindow", "Philippines"))
        self.tab02_select_reporter.setItemText(210, _translate("MainWindow", "Pitcairn"))
        self.tab02_select_reporter.setItemText(211, _translate("MainWindow", "Poland"))
        self.tab02_select_reporter.setItemText(212, _translate("MainWindow", "Portugal"))
        self.tab02_select_reporter.setItemText(213, _translate("MainWindow", "Qatar"))
        self.tab02_select_reporter.setItemText(214, _translate("MainWindow", "Rep. of Korea"))
        self.tab02_select_reporter.setItemText(215, _translate("MainWindow", "Rep. of Moldova"))
        self.tab02_select_reporter.setItemText(216, _translate("MainWindow", "Rest of America, nes"))
        self.tab02_select_reporter.setItemText(217, _translate("MainWindow", "Réunion"))
        self.tab02_select_reporter.setItemText(218, _translate("MainWindow", "Romania"))
        self.tab02_select_reporter.setItemText(219, _translate("MainWindow", "Russian Federation"))
        self.tab02_select_reporter.setItemText(220, _translate("MainWindow", "Rwanda"))
        self.tab02_select_reporter.setItemText(221, _translate("MainWindow", "Ryukyu Isd"))
        self.tab02_select_reporter.setItemText(222, _translate("MainWindow", "Sabah"))
        self.tab02_select_reporter.setItemText(223, _translate("MainWindow", "Saint Helena"))
        self.tab02_select_reporter.setItemText(224, _translate("MainWindow", "Saint Kitts and Nevis"))
        self.tab02_select_reporter.setItemText(225, _translate("MainWindow", "Saint Kitts, Nevis and Anguilla"))
        self.tab02_select_reporter.setItemText(226, _translate("MainWindow", "Saint Lucia"))
        self.tab02_select_reporter.setItemText(227, _translate("MainWindow", "Saint Maarten"))
        self.tab02_select_reporter.setItemText(228, _translate("MainWindow", "Saint Pierre and Miquelon"))
        self.tab02_select_reporter.setItemText(229, _translate("MainWindow", "Saint Vincent and the Grenadines"))
        self.tab02_select_reporter.setItemText(230, _translate("MainWindow", "Samoa"))
        self.tab02_select_reporter.setItemText(231, _translate("MainWindow", "San Marino"))
        self.tab02_select_reporter.setItemText(232, _translate("MainWindow", "Sao Tome and Principe"))
        self.tab02_select_reporter.setItemText(233, _translate("MainWindow", "Sarawak"))
        self.tab02_select_reporter.setItemText(234, _translate("MainWindow", "Saudi Arabia"))
        self.tab02_select_reporter.setItemText(235, _translate("MainWindow", "Senegal"))
        self.tab02_select_reporter.setItemText(236, _translate("MainWindow", "Serbia"))
        self.tab02_select_reporter.setItemText(237, _translate("MainWindow", "Serbia and Montenegro"))
        self.tab02_select_reporter.setItemText(238, _translate("MainWindow", "Seychelles"))
        self.tab02_select_reporter.setItemText(239, _translate("MainWindow", "Sierra Leone"))
        self.tab02_select_reporter.setItemText(240, _translate("MainWindow", "Sikkim"))
        self.tab02_select_reporter.setItemText(241, _translate("MainWindow", "Singapore"))
        self.tab02_select_reporter.setItemText(242, _translate("MainWindow", "Slovakia"))
        self.tab02_select_reporter.setItemText(243, _translate("MainWindow", "Slovenia"))
        self.tab02_select_reporter.setItemText(244, _translate("MainWindow", "So. African Customs Union"))
        self.tab02_select_reporter.setItemText(245, _translate("MainWindow", "Solomon Isds"))
        self.tab02_select_reporter.setItemText(246, _translate("MainWindow", "Somalia"))
        self.tab02_select_reporter.setItemText(247, _translate("MainWindow", "South Africa"))
        self.tab02_select_reporter.setItemText(248, _translate("MainWindow", "South Georgia and the South Sandwich Islands"))
        self.tab02_select_reporter.setItemText(249, _translate("MainWindow", "South Sudan"))
        self.tab02_select_reporter.setItemText(250, _translate("MainWindow", "Spain"))
        self.tab02_select_reporter.setItemText(251, _translate("MainWindow", "Special Categories"))
        self.tab02_select_reporter.setItemText(252, _translate("MainWindow", "Sri Lanka"))
        self.tab02_select_reporter.setItemText(253, _translate("MainWindow", "State of Palestine"))
        self.tab02_select_reporter.setItemText(254, _translate("MainWindow", "Sudan"))
        self.tab02_select_reporter.setItemText(255, _translate("MainWindow", "Suriname"))
        self.tab02_select_reporter.setItemText(256, _translate("MainWindow", "Swaziland"))
        self.tab02_select_reporter.setItemText(257, _translate("MainWindow", "Sweden"))
        self.tab02_select_reporter.setItemText(258, _translate("MainWindow", "Switzerland"))
        self.tab02_select_reporter.setItemText(259, _translate("MainWindow", "Syria"))
        self.tab02_select_reporter.setItemText(260, _translate("MainWindow", "Tajikistan"))
        self.tab02_select_reporter.setItemText(261, _translate("MainWindow", "TFYR of Macedonia"))
        self.tab02_select_reporter.setItemText(262, _translate("MainWindow", "Thailand"))
        self.tab02_select_reporter.setItemText(263, _translate("MainWindow", "Timor-Leste"))
        self.tab02_select_reporter.setItemText(264, _translate("MainWindow", "Togo"))
        self.tab02_select_reporter.setItemText(265, _translate("MainWindow", "Tokelau"))
        self.tab02_select_reporter.setItemText(266, _translate("MainWindow", "Tonga"))
        self.tab02_select_reporter.setItemText(267, _translate("MainWindow", "Trinidad and Tobago"))
        self.tab02_select_reporter.setItemText(268, _translate("MainWindow", "Tunisia"))
        self.tab02_select_reporter.setItemText(269, _translate("MainWindow", "Turkey"))
        self.tab02_select_reporter.setItemText(270, _translate("MainWindow", "Turkmenistan"))
        self.tab02_select_reporter.setItemText(271, _translate("MainWindow", "Turks and Caicos Isds"))
        self.tab02_select_reporter.setItemText(272, _translate("MainWindow", "Tuvalu"))
        self.tab02_select_reporter.setItemText(273, _translate("MainWindow", "Uganda"))
        self.tab02_select_reporter.setItemText(274, _translate("MainWindow", "Ukraine"))
        self.tab02_select_reporter.setItemText(275, _translate("MainWindow", "United Arab Emirates"))
        self.tab02_select_reporter.setItemText(276, _translate("MainWindow", "United Kingdom"))
        self.tab02_select_reporter.setItemText(277, _translate("MainWindow", "United Rep. of Tanzania"))
        self.tab02_select_reporter.setItemText(278, _translate("MainWindow", "United States Minor Outlying Islands"))
        self.tab02_select_reporter.setItemText(279, _translate("MainWindow", "Uruguay"))
        self.tab02_select_reporter.setItemText(280, _translate("MainWindow", "US Misc. Pacific Isds"))
        self.tab02_select_reporter.setItemText(281, _translate("MainWindow", "US Virgin Isds"))
        self.tab02_select_reporter.setItemText(282, _translate("MainWindow", "USA"))
        self.tab02_select_reporter.setItemText(283, _translate("MainWindow", "USA (before 1981)"))
        self.tab02_select_reporter.setItemText(284, _translate("MainWindow", "Uzbekistan"))
        self.tab02_select_reporter.setItemText(285, _translate("MainWindow", "Vanuatu"))
        self.tab02_select_reporter.setItemText(286, _translate("MainWindow", "Venezuela"))
        self.tab02_select_reporter.setItemText(287, _translate("MainWindow", "Viet Nam"))
        self.tab02_select_reporter.setItemText(288, _translate("MainWindow", "Wallis and Futuna Isds"))
        self.tab02_select_reporter.setItemText(289, _translate("MainWindow", "Western Asia, nes"))
        self.tab02_select_reporter.setItemText(290, _translate("MainWindow", "Western Sahara"))
        self.tab02_select_reporter.setItemText(291, _translate("MainWindow", "Yemen"))
        self.tab02_select_reporter.setItemText(292, _translate("MainWindow", "Zambia"))
        self.tab02_select_reporter.setItemText(293, _translate("MainWindow", "Zimbabwe"))
        self.tab03_select_partner.setItemText(0, _translate("MainWindow", "None"))
        self.tab03_select_partner.setItemText(1, _translate("MainWindow", "All"))
        self.tab03_select_partner.setItemText(2, _translate("MainWindow", "World"))
        self.tab03_select_partner.setItemText(3, _translate("MainWindow", "Afghanistan"))
        self.tab03_select_partner.setItemText(4, _translate("MainWindow", "Africa CAMEU region, nes"))
        self.tab03_select_partner.setItemText(5, _translate("MainWindow", "Albania"))
        self.tab03_select_partner.setItemText(6, _translate("MainWindow", "Algeria"))
        self.tab03_select_partner.setItemText(7, _translate("MainWindow", "American Samoa"))
        self.tab03_select_partner.setItemText(8, _translate("MainWindow", "Andorra"))
        self.tab03_select_partner.setItemText(9, _translate("MainWindow", "Angola"))
        self.tab03_select_partner.setItemText(10, _translate("MainWindow", "Anguilla"))
        self.tab03_select_partner.setItemText(11, _translate("MainWindow", "Antarctica"))
        self.tab03_select_partner.setItemText(12, _translate("MainWindow", "Antigua and Barbuda"))
        self.tab03_select_partner.setItemText(13, _translate("MainWindow", "Areas, nes"))
        self.tab03_select_partner.setItemText(14, _translate("MainWindow", "Argentina"))
        self.tab03_select_partner.setItemText(15, _translate("MainWindow", "Armenia"))
        self.tab03_select_partner.setItemText(16, _translate("MainWindow", "Aruba"))
        self.tab03_select_partner.setItemText(17, _translate("MainWindow", "Australia"))
        self.tab03_select_partner.setItemText(18, _translate("MainWindow", "Austria"))
        self.tab03_select_partner.setItemText(19, _translate("MainWindow", "Azerbaijan"))
        self.tab03_select_partner.setItemText(20, _translate("MainWindow", "Bahamas"))
        self.tab03_select_partner.setItemText(21, _translate("MainWindow", "Bahrain"))
        self.tab03_select_partner.setItemText(22, _translate("MainWindow", "Bangladesh"))
        self.tab03_select_partner.setItemText(23, _translate("MainWindow", "Barbados"))
        self.tab03_select_partner.setItemText(24, _translate("MainWindow", "Belarus"))
        self.tab03_select_partner.setItemText(25, _translate("MainWindow", "Belgium"))
        self.tab03_select_partner.setItemText(26, _translate("MainWindow", "Belgium-Luxembourg"))
        self.tab03_select_partner.setItemText(27, _translate("MainWindow", "Belize"))
        self.tab03_select_partner.setItemText(28, _translate("MainWindow", "Benin"))
        self.tab03_select_partner.setItemText(29, _translate("MainWindow", "Bermuda"))
        self.tab03_select_partner.setItemText(30, _translate("MainWindow", "Bhutan"))
        self.tab03_select_partner.setItemText(31, _translate("MainWindow", "Bolivia (Plurinational State of)"))
        self.tab03_select_partner.setItemText(32, _translate("MainWindow", "Bonaire"))
        self.tab03_select_partner.setItemText(33, _translate("MainWindow", "Bosnia Herzegovina"))
        self.tab03_select_partner.setItemText(34, _translate("MainWindow", "Botswana"))
        self.tab03_select_partner.setItemText(35, _translate("MainWindow", "Bouvet Island"))
        self.tab03_select_partner.setItemText(36, _translate("MainWindow", "Br. Antarctic Terr."))
        self.tab03_select_partner.setItemText(37, _translate("MainWindow", "Br. Indian Ocean Terr."))
        self.tab03_select_partner.setItemText(38, _translate("MainWindow", "Br. Virgin Isds"))
        self.tab03_select_partner.setItemText(39, _translate("MainWindow", "Brazil"))
        self.tab03_select_partner.setItemText(40, _translate("MainWindow", "Brunei Darussalam"))
        self.tab03_select_partner.setItemText(41, _translate("MainWindow", "Bulgaria"))
        self.tab03_select_partner.setItemText(42, _translate("MainWindow", "Bunkers"))
        self.tab03_select_partner.setItemText(43, _translate("MainWindow", "Burkina Faso"))
        self.tab03_select_partner.setItemText(44, _translate("MainWindow", "Burundi"))
        self.tab03_select_partner.setItemText(45, _translate("MainWindow", "Cabo Verde"))
        self.tab03_select_partner.setItemText(46, _translate("MainWindow", "CACM, nes"))
        self.tab03_select_partner.setItemText(47, _translate("MainWindow", "Cambodia"))
        self.tab03_select_partner.setItemText(48, _translate("MainWindow", "Cameroon"))
        self.tab03_select_partner.setItemText(49, _translate("MainWindow", "Canada"))
        self.tab03_select_partner.setItemText(50, _translate("MainWindow", "Caribbean, nes"))
        self.tab03_select_partner.setItemText(51, _translate("MainWindow", "Cayman Isds"))
        self.tab03_select_partner.setItemText(52, _translate("MainWindow", "Central African Rep."))
        self.tab03_select_partner.setItemText(53, _translate("MainWindow", "Chad"))
        self.tab03_select_partner.setItemText(54, _translate("MainWindow", "Chile"))
        self.tab03_select_partner.setItemText(55, _translate("MainWindow", "China"))
        self.tab03_select_partner.setItemText(56, _translate("MainWindow", "China, Hong Kong SAR"))
        self.tab03_select_partner.setItemText(57, _translate("MainWindow", "China, Macao SAR"))
        self.tab03_select_partner.setItemText(58, _translate("MainWindow", "Christmas Isds"))
        self.tab03_select_partner.setItemText(59, _translate("MainWindow", "Cocos Isds"))
        self.tab03_select_partner.setItemText(60, _translate("MainWindow", "Colombia"))
        self.tab03_select_partner.setItemText(61, _translate("MainWindow", "Comoros"))
        self.tab03_select_partner.setItemText(62, _translate("MainWindow", "Congo"))
        self.tab03_select_partner.setItemText(63, _translate("MainWindow", "Cook Isds"))
        self.tab03_select_partner.setItemText(64, _translate("MainWindow", "Costa Rica"))
        self.tab03_select_partner.setItemText(65, _translate("MainWindow", "Côte d\'Ivoire"))
        self.tab03_select_partner.setItemText(66, _translate("MainWindow", "Croatia"))
        self.tab03_select_partner.setItemText(67, _translate("MainWindow", "Cuba"))
        self.tab03_select_partner.setItemText(68, _translate("MainWindow", "Curaçao"))
        self.tab03_select_partner.setItemText(69, _translate("MainWindow", "Cyprus"))
        self.tab03_select_partner.setItemText(70, _translate("MainWindow", "Czechia"))
        self.tab03_select_partner.setItemText(71, _translate("MainWindow", "Czechoslovakia"))
        self.tab03_select_partner.setItemText(72, _translate("MainWindow", "Dem. People\'s Rep. of Korea"))
        self.tab03_select_partner.setItemText(73, _translate("MainWindow", "Dem. Rep. of the Congo"))
        self.tab03_select_partner.setItemText(74, _translate("MainWindow", "Denmark"))
        self.tab03_select_partner.setItemText(75, _translate("MainWindow", "Djibouti"))
        self.tab03_select_partner.setItemText(76, _translate("MainWindow", "Dominica"))
        self.tab03_select_partner.setItemText(77, _translate("MainWindow", "Dominican Rep."))
        self.tab03_select_partner.setItemText(78, _translate("MainWindow", "East and West Pakistan"))
        self.tab03_select_partner.setItemText(79, _translate("MainWindow", "Eastern Europe, nes"))
        self.tab03_select_partner.setItemText(80, _translate("MainWindow", "Ecuador"))
        self.tab03_select_partner.setItemText(81, _translate("MainWindow", "Egypt"))
        self.tab03_select_partner.setItemText(82, _translate("MainWindow", "El Salvador"))
        self.tab03_select_partner.setItemText(83, _translate("MainWindow", "Equatorial Guinea"))
        self.tab03_select_partner.setItemText(84, _translate("MainWindow", "Eritrea"))
        self.tab03_select_partner.setItemText(85, _translate("MainWindow", "Estonia"))
        self.tab03_select_partner.setItemText(86, _translate("MainWindow", "Ethiopia"))
        self.tab03_select_partner.setItemText(87, _translate("MainWindow", "Europe EFTA, nes"))
        self.tab03_select_partner.setItemText(88, _translate("MainWindow", "Europe EU, nes"))
        self.tab03_select_partner.setItemText(89, _translate("MainWindow", "Faeroe Isds"))
        self.tab03_select_partner.setItemText(90, _translate("MainWindow", "Falkland Isds (Malvinas)"))
        self.tab03_select_partner.setItemText(91, _translate("MainWindow", "Fiji"))
        self.tab03_select_partner.setItemText(92, _translate("MainWindow", "Finland"))
        self.tab03_select_partner.setItemText(93, _translate("MainWindow", "Fmr Arab Rep. of Yemen"))
        self.tab03_select_partner.setItemText(94, _translate("MainWindow", "Fmr Dem. Rep. of Germany"))
        self.tab03_select_partner.setItemText(95, _translate("MainWindow", "Fmr Dem. Rep. of Vietnam"))
        self.tab03_select_partner.setItemText(96, _translate("MainWindow", "Fmr Dem. Yemen"))
        self.tab03_select_partner.setItemText(97, _translate("MainWindow", "Fmr Ethiopia"))
        self.tab03_select_partner.setItemText(98, _translate("MainWindow", "Fmr Fed. Rep. of Germany"))
        self.tab03_select_partner.setItemText(99, _translate("MainWindow", "Fmr Pacific Isds"))
        self.tab03_select_partner.setItemText(100, _translate("MainWindow", "Fmr Panama, excl.Canal Zone"))
        self.tab03_select_partner.setItemText(101, _translate("MainWindow", "Fmr Panama-Canal-Zone"))
        self.tab03_select_partner.setItemText(102, _translate("MainWindow", "Fmr Rep. of Vietnam"))
        self.tab03_select_partner.setItemText(103, _translate("MainWindow", "Fmr Rhodesia Nyas"))
        self.tab03_select_partner.setItemText(104, _translate("MainWindow", "Fmr Sudan"))
        self.tab03_select_partner.setItemText(105, _translate("MainWindow", "Fmr Tanganyika"))
        self.tab03_select_partner.setItemText(106, _translate("MainWindow", "Fmr USSR"))
        self.tab03_select_partner.setItemText(107, _translate("MainWindow", "Fmr Yugoslavia"))
        self.tab03_select_partner.setItemText(108, _translate("MainWindow", "Fmr Zanzibar and Pemba Isd"))
        self.tab03_select_partner.setItemText(109, _translate("MainWindow", "Fr. South Antarctic Terr."))
        self.tab03_select_partner.setItemText(110, _translate("MainWindow", "France"))
        self.tab03_select_partner.setItemText(111, _translate("MainWindow", "Free Zones"))
        self.tab03_select_partner.setItemText(112, _translate("MainWindow", "French Guiana"))
        self.tab03_select_partner.setItemText(113, _translate("MainWindow", "French Polynesia"))
        self.tab03_select_partner.setItemText(114, _translate("MainWindow", "FS Micronesia"))
        self.tab03_select_partner.setItemText(115, _translate("MainWindow", "Gabon"))
        self.tab03_select_partner.setItemText(116, _translate("MainWindow", "Gambia"))
        self.tab03_select_partner.setItemText(117, _translate("MainWindow", "Georgia"))
        self.tab03_select_partner.setItemText(118, _translate("MainWindow", "Germany"))
        self.tab03_select_partner.setItemText(119, _translate("MainWindow", "Ghana"))
        self.tab03_select_partner.setItemText(120, _translate("MainWindow", "Gibraltar"))
        self.tab03_select_partner.setItemText(121, _translate("MainWindow", "Greece"))
        self.tab03_select_partner.setItemText(122, _translate("MainWindow", "Greenland"))
        self.tab03_select_partner.setItemText(123, _translate("MainWindow", "Grenada"))
        self.tab03_select_partner.setItemText(124, _translate("MainWindow", "Guadeloupe"))
        self.tab03_select_partner.setItemText(125, _translate("MainWindow", "Guam"))
        self.tab03_select_partner.setItemText(126, _translate("MainWindow", "Guatemala"))
        self.tab03_select_partner.setItemText(127, _translate("MainWindow", "Guinea"))
        self.tab03_select_partner.setItemText(128, _translate("MainWindow", "Guinea-Bissau"))
        self.tab03_select_partner.setItemText(129, _translate("MainWindow", "Guyana"))
        self.tab03_select_partner.setItemText(130, _translate("MainWindow", "Haiti"))
        self.tab03_select_partner.setItemText(131, _translate("MainWindow", "Heard Island and McDonald Islands"))
        self.tab03_select_partner.setItemText(132, _translate("MainWindow", "Holy See (Vatican City State)"))
        self.tab03_select_partner.setItemText(133, _translate("MainWindow", "Honduras"))
        self.tab03_select_partner.setItemText(134, _translate("MainWindow", "Hungary"))
        self.tab03_select_partner.setItemText(135, _translate("MainWindow", "Iceland"))
        self.tab03_select_partner.setItemText(136, _translate("MainWindow", "India"))
        self.tab03_select_partner.setItemText(137, _translate("MainWindow", "India, excl. Sikkim"))
        self.tab03_select_partner.setItemText(138, _translate("MainWindow", "Indonesia"))
        self.tab03_select_partner.setItemText(139, _translate("MainWindow", "Iran"))
        self.tab03_select_partner.setItemText(140, _translate("MainWindow", "Iraq"))
        self.tab03_select_partner.setItemText(141, _translate("MainWindow", "Ireland"))
        self.tab03_select_partner.setItemText(142, _translate("MainWindow", "Israel"))
        self.tab03_select_partner.setItemText(143, _translate("MainWindow", "Italy"))
        self.tab03_select_partner.setItemText(144, _translate("MainWindow", "Jamaica"))
        self.tab03_select_partner.setItemText(145, _translate("MainWindow", "Japan"))
        self.tab03_select_partner.setItemText(146, _translate("MainWindow", "Jordan"))
        self.tab03_select_partner.setItemText(147, _translate("MainWindow", "Kazakhstan"))
        self.tab03_select_partner.setItemText(148, _translate("MainWindow", "Kenya"))
        self.tab03_select_partner.setItemText(149, _translate("MainWindow", "Kiribati"))
        self.tab03_select_partner.setItemText(150, _translate("MainWindow", "Kuwait"))
        self.tab03_select_partner.setItemText(151, _translate("MainWindow", "Kyrgyzstan"))
        self.tab03_select_partner.setItemText(152, _translate("MainWindow", "LAIA, nes"))
        self.tab03_select_partner.setItemText(153, _translate("MainWindow", "Lao People\'s Dem. Rep."))
        self.tab03_select_partner.setItemText(154, _translate("MainWindow", "Latvia"))
        self.tab03_select_partner.setItemText(155, _translate("MainWindow", "Lebanon"))
        self.tab03_select_partner.setItemText(156, _translate("MainWindow", "Lesotho"))
        self.tab03_select_partner.setItemText(157, _translate("MainWindow", "Liberia"))
        self.tab03_select_partner.setItemText(158, _translate("MainWindow", "Libya"))
        self.tab03_select_partner.setItemText(159, _translate("MainWindow", "Lithuania"))
        self.tab03_select_partner.setItemText(160, _translate("MainWindow", "Luxembourg"))
        self.tab03_select_partner.setItemText(161, _translate("MainWindow", "Madagascar"))
        self.tab03_select_partner.setItemText(162, _translate("MainWindow", "Malawi"))
        self.tab03_select_partner.setItemText(163, _translate("MainWindow", "Malaysia"))
        self.tab03_select_partner.setItemText(164, _translate("MainWindow", "Maldives"))
        self.tab03_select_partner.setItemText(165, _translate("MainWindow", "Mali"))
        self.tab03_select_partner.setItemText(166, _translate("MainWindow", "Malta"))
        self.tab03_select_partner.setItemText(167, _translate("MainWindow", "Marshall Isds"))
        self.tab03_select_partner.setItemText(168, _translate("MainWindow", "Martinique"))
        self.tab03_select_partner.setItemText(169, _translate("MainWindow", "Mauritania"))
        self.tab03_select_partner.setItemText(170, _translate("MainWindow", "Mauritius"))
        self.tab03_select_partner.setItemText(171, _translate("MainWindow", "Mayotte"))
        self.tab03_select_partner.setItemText(172, _translate("MainWindow", "Mexico"))
        self.tab03_select_partner.setItemText(173, _translate("MainWindow", "Mongolia"))
        self.tab03_select_partner.setItemText(174, _translate("MainWindow", "Montenegro"))
        self.tab03_select_partner.setItemText(175, _translate("MainWindow", "Montserrat"))
        self.tab03_select_partner.setItemText(176, _translate("MainWindow", "Morocco"))
        self.tab03_select_partner.setItemText(177, _translate("MainWindow", "Mozambique"))
        self.tab03_select_partner.setItemText(178, _translate("MainWindow", "Myanmar"))
        self.tab03_select_partner.setItemText(179, _translate("MainWindow", "N. Mariana Isds"))
        self.tab03_select_partner.setItemText(180, _translate("MainWindow", "Namibia"))
        self.tab03_select_partner.setItemText(181, _translate("MainWindow", "Nauru"))
        self.tab03_select_partner.setItemText(182, _translate("MainWindow", "Nepal"))
        self.tab03_select_partner.setItemText(183, _translate("MainWindow", "Neth. Antilles"))
        self.tab03_select_partner.setItemText(184, _translate("MainWindow", "Neth. Antilles and Aruba"))
        self.tab03_select_partner.setItemText(185, _translate("MainWindow", "Netherlands"))
        self.tab03_select_partner.setItemText(186, _translate("MainWindow", "Neutral Zone"))
        self.tab03_select_partner.setItemText(187, _translate("MainWindow", "New Caledonia"))
        self.tab03_select_partner.setItemText(188, _translate("MainWindow", "New Zealand"))
        self.tab03_select_partner.setItemText(189, _translate("MainWindow", "Nicaragua"))
        self.tab03_select_partner.setItemText(190, _translate("MainWindow", "Niger"))
        self.tab03_select_partner.setItemText(191, _translate("MainWindow", "Nigeria"))
        self.tab03_select_partner.setItemText(192, _translate("MainWindow", "Niue"))
        self.tab03_select_partner.setItemText(193, _translate("MainWindow", "Norfolk Isds"))
        self.tab03_select_partner.setItemText(194, _translate("MainWindow", "North America and Central America, nes"))
        self.tab03_select_partner.setItemText(195, _translate("MainWindow", "Northern Africa, nes"))
        self.tab03_select_partner.setItemText(196, _translate("MainWindow", "Norway"))
        self.tab03_select_partner.setItemText(197, _translate("MainWindow", "Oceania, nes"))
        self.tab03_select_partner.setItemText(198, _translate("MainWindow", "Oman"))
        self.tab03_select_partner.setItemText(199, _translate("MainWindow", "Other Africa, nes"))
        self.tab03_select_partner.setItemText(200, _translate("MainWindow", "Other Asia, nes"))
        self.tab03_select_partner.setItemText(201, _translate("MainWindow", "Other Europe, nes"))
        self.tab03_select_partner.setItemText(202, _translate("MainWindow", "Pakistan"))
        self.tab03_select_partner.setItemText(203, _translate("MainWindow", "Palau"))
        self.tab03_select_partner.setItemText(204, _translate("MainWindow", "Panama"))
        self.tab03_select_partner.setItemText(205, _translate("MainWindow", "Papua New Guinea"))
        self.tab03_select_partner.setItemText(206, _translate("MainWindow", "Paraguay"))
        self.tab03_select_partner.setItemText(207, _translate("MainWindow", "Peninsula Malaysia"))
        self.tab03_select_partner.setItemText(208, _translate("MainWindow", "Peru"))
        self.tab03_select_partner.setItemText(209, _translate("MainWindow", "Philippines"))
        self.tab03_select_partner.setItemText(210, _translate("MainWindow", "Pitcairn"))
        self.tab03_select_partner.setItemText(211, _translate("MainWindow", "Poland"))
        self.tab03_select_partner.setItemText(212, _translate("MainWindow", "Portugal"))
        self.tab03_select_partner.setItemText(213, _translate("MainWindow", "Qatar"))
        self.tab03_select_partner.setItemText(214, _translate("MainWindow", "Rep. of Korea"))
        self.tab03_select_partner.setItemText(215, _translate("MainWindow", "Rep. of Moldova"))
        self.tab03_select_partner.setItemText(216, _translate("MainWindow", "Rest of America, nes"))
        self.tab03_select_partner.setItemText(217, _translate("MainWindow", "Réunion"))
        self.tab03_select_partner.setItemText(218, _translate("MainWindow", "Romania"))
        self.tab03_select_partner.setItemText(219, _translate("MainWindow", "Russian Federation"))
        self.tab03_select_partner.setItemText(220, _translate("MainWindow", "Rwanda"))
        self.tab03_select_partner.setItemText(221, _translate("MainWindow", "Ryukyu Isd"))
        self.tab03_select_partner.setItemText(222, _translate("MainWindow", "Sabah"))
        self.tab03_select_partner.setItemText(223, _translate("MainWindow", "Saint Helena"))
        self.tab03_select_partner.setItemText(224, _translate("MainWindow", "Saint Kitts and Nevis"))
        self.tab03_select_partner.setItemText(225, _translate("MainWindow", "Saint Kitts, Nevis and Anguilla"))
        self.tab03_select_partner.setItemText(226, _translate("MainWindow", "Saint Lucia"))
        self.tab03_select_partner.setItemText(227, _translate("MainWindow", "Saint Maarten"))
        self.tab03_select_partner.setItemText(228, _translate("MainWindow", "Saint Pierre and Miquelon"))
        self.tab03_select_partner.setItemText(229, _translate("MainWindow", "Saint Vincent and the Grenadines"))
        self.tab03_select_partner.setItemText(230, _translate("MainWindow", "Samoa"))
        self.tab03_select_partner.setItemText(231, _translate("MainWindow", "San Marino"))
        self.tab03_select_partner.setItemText(232, _translate("MainWindow", "Sao Tome and Principe"))
        self.tab03_select_partner.setItemText(233, _translate("MainWindow", "Sarawak"))
        self.tab03_select_partner.setItemText(234, _translate("MainWindow", "Saudi Arabia"))
        self.tab03_select_partner.setItemText(235, _translate("MainWindow", "Senegal"))
        self.tab03_select_partner.setItemText(236, _translate("MainWindow", "Serbia"))
        self.tab03_select_partner.setItemText(237, _translate("MainWindow", "Serbia and Montenegro"))
        self.tab03_select_partner.setItemText(238, _translate("MainWindow", "Seychelles"))
        self.tab03_select_partner.setItemText(239, _translate("MainWindow", "Sierra Leone"))
        self.tab03_select_partner.setItemText(240, _translate("MainWindow", "Sikkim"))
        self.tab03_select_partner.setItemText(241, _translate("MainWindow", "Singapore"))
        self.tab03_select_partner.setItemText(242, _translate("MainWindow", "Slovakia"))
        self.tab03_select_partner.setItemText(243, _translate("MainWindow", "Slovenia"))
        self.tab03_select_partner.setItemText(244, _translate("MainWindow", "So. African Customs Union"))
        self.tab03_select_partner.setItemText(245, _translate("MainWindow", "Solomon Isds"))
        self.tab03_select_partner.setItemText(246, _translate("MainWindow", "Somalia"))
        self.tab03_select_partner.setItemText(247, _translate("MainWindow", "South Africa"))
        self.tab03_select_partner.setItemText(248, _translate("MainWindow", "South Georgia and the South Sandwich Islands"))
        self.tab03_select_partner.setItemText(249, _translate("MainWindow", "South Sudan"))
        self.tab03_select_partner.setItemText(250, _translate("MainWindow", "Spain"))
        self.tab03_select_partner.setItemText(251, _translate("MainWindow", "Special Categories"))
        self.tab03_select_partner.setItemText(252, _translate("MainWindow", "Sri Lanka"))
        self.tab03_select_partner.setItemText(253, _translate("MainWindow", "State of Palestine"))
        self.tab03_select_partner.setItemText(254, _translate("MainWindow", "Sudan"))
        self.tab03_select_partner.setItemText(255, _translate("MainWindow", "Suriname"))
        self.tab03_select_partner.setItemText(256, _translate("MainWindow", "Swaziland"))
        self.tab03_select_partner.setItemText(257, _translate("MainWindow", "Sweden"))
        self.tab03_select_partner.setItemText(258, _translate("MainWindow", "Switzerland"))
        self.tab03_select_partner.setItemText(259, _translate("MainWindow", "Syria"))
        self.tab03_select_partner.setItemText(260, _translate("MainWindow", "Tajikistan"))
        self.tab03_select_partner.setItemText(261, _translate("MainWindow", "TFYR of Macedonia"))
        self.tab03_select_partner.setItemText(262, _translate("MainWindow", "Thailand"))
        self.tab03_select_partner.setItemText(263, _translate("MainWindow", "Timor-Leste"))
        self.tab03_select_partner.setItemText(264, _translate("MainWindow", "Togo"))
        self.tab03_select_partner.setItemText(265, _translate("MainWindow", "Tokelau"))
        self.tab03_select_partner.setItemText(266, _translate("MainWindow", "Tonga"))
        self.tab03_select_partner.setItemText(267, _translate("MainWindow", "Trinidad and Tobago"))
        self.tab03_select_partner.setItemText(268, _translate("MainWindow", "Tunisia"))
        self.tab03_select_partner.setItemText(269, _translate("MainWindow", "Turkey"))
        self.tab03_select_partner.setItemText(270, _translate("MainWindow", "Turkmenistan"))
        self.tab03_select_partner.setItemText(271, _translate("MainWindow", "Turks and Caicos Isds"))
        self.tab03_select_partner.setItemText(272, _translate("MainWindow", "Tuvalu"))
        self.tab03_select_partner.setItemText(273, _translate("MainWindow", "Uganda"))
        self.tab03_select_partner.setItemText(274, _translate("MainWindow", "Ukraine"))
        self.tab03_select_partner.setItemText(275, _translate("MainWindow", "United Arab Emirates"))
        self.tab03_select_partner.setItemText(276, _translate("MainWindow", "United Kingdom"))
        self.tab03_select_partner.setItemText(277, _translate("MainWindow", "United Rep. of Tanzania"))
        self.tab03_select_partner.setItemText(278, _translate("MainWindow", "United States Minor Outlying Islands"))
        self.tab03_select_partner.setItemText(279, _translate("MainWindow", "Uruguay"))
        self.tab03_select_partner.setItemText(280, _translate("MainWindow", "US Misc. Pacific Isds"))
        self.tab03_select_partner.setItemText(281, _translate("MainWindow", "US Virgin Isds"))
        self.tab03_select_partner.setItemText(282, _translate("MainWindow", "USA"))
        self.tab03_select_partner.setItemText(283, _translate("MainWindow", "USA (before 1981)"))
        self.tab03_select_partner.setItemText(284, _translate("MainWindow", "Uzbekistan"))
        self.tab03_select_partner.setItemText(285, _translate("MainWindow", "Vanuatu"))
        self.tab03_select_partner.setItemText(286, _translate("MainWindow", "Venezuela"))
        self.tab03_select_partner.setItemText(287, _translate("MainWindow", "Viet Nam"))
        self.tab03_select_partner.setItemText(288, _translate("MainWindow", "Wallis and Futuna Isds"))
        self.tab03_select_partner.setItemText(289, _translate("MainWindow", "Western Asia, nes"))
        self.tab03_select_partner.setItemText(290, _translate("MainWindow", "Western Sahara"))
        self.tab03_select_partner.setItemText(291, _translate("MainWindow", "Yemen"))
        self.tab03_select_partner.setItemText(292, _translate("MainWindow", "Zambia"))
        self.tab03_select_partner.setItemText(293, _translate("MainWindow", "Zimbabwe"))
        self.tab04_select_trade_flow.setItemText(0, _translate("MainWindow", "None"))
        self.tab04_select_trade_flow.setItemText(1, _translate("MainWindow", "All"))
        self.tab04_select_trade_flow.setItemText(2, _translate("MainWindow", "Import"))
        self.tab04_select_trade_flow.setItemText(3, _translate("MainWindow", "Export"))
        self.tab04_select_trade_flow.setItemText(4, _translate("MainWindow", "re-Import"))
        self.tab04_select_trade_flow.setItemText(5, _translate("MainWindow", "re-Export"))
        self.label_name_start_index.setText(_translate("MainWindow", "Start Index    :"))
        self.tab09_input_start_index.setText(_translate("MainWindow", "0"))
        self.btn_get_data.setText(_translate("MainWindow", "Get Data"))
        self.text_message.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_name_end_index.setText(_translate("MainWindow", "End Index     :"))
        self.tab10_input_end_index.setText(_translate("MainWindow", "0"))
        self.tab05_radio_freq_year.setText(_translate("MainWindow", "Annual"))
        self.tab06_radio_freq_month.setText(_translate("MainWindow", "Monthly"))
        self.check_5.setText(_translate("MainWindow", "May"))
        self.check_all.setText(_translate("MainWindow", "All"))
        self.check_7.setText(_translate("MainWindow", "July"))
        self.check_6.setText(_translate("MainWindow", "June"))
        self.check_8.setText(_translate("MainWindow", "Augest"))
        self.check_1.setText(_translate("MainWindow", "January"))
        self.check_9.setText(_translate("MainWindow", "September"))
        self.check_10.setText(_translate("MainWindow", "October"))
        self.check_11.setText(_translate("MainWindow", "November"))
        self.check_12.setText(_translate("MainWindow", "December"))
        self.check_2.setText(_translate("MainWindow", "February"))
        self.check_4.setText(_translate("MainWindow", "April"))
        self.check_3.setText(_translate("MainWindow", "March"))
        self.label_name_start_hs.setText(_translate("MainWindow", "Start HS Code :"))
        self.label_name_end_hs.setText(_translate("MainWindow", "End HS Code  :"))
        self.tab11_input_start_hs.setText(_translate("MainWindow", "0"))
        self.tab12_input_end_hs.setText(_translate("MainWindow", "0"))
        self.tab07_radio_index.setText(_translate("MainWindow", "Get data by Index"))
        self.tab08_radio_hs.setText(_translate("MainWindow", "Get data by HS Code"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
